version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # This uses the correct, pre-installed version
  build:
    commands:
      - echo "Fixing line endings and permissions for $SERVICE_NAME..."
      # Use the folder prefix so sed can find the files
      - sed -i 's/\r$//' products/scripts/*.sh
      - chmod +x products/scripts/*.sh
artifacts:
  files:
    - '**/*'
  # This flattens the zip so appspec.yml is at the root
  base-directory: 'products'