version: 0.2

env:
  secrets-manager:
    MONGODB_URI: "microservices-secrets-v6:CUSTOMER_DB_URI"
    MSG_QUEUE_URL: "microservices-secrets-v6:MSG_QUEUE_URL"
    EXCHANGE_NAME: "microservices-secrets-v6:EXCHANGE_NAME"
    APP_SECRET: "microservices-secrets-v6:APP_SECRET"
    NODE_ENV: "microservices-secrets-v6:NODE_ENV"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd customer
      - npm install
  pre_build:
    commands:
      - echo "Generating .env file with SSL certificate path..."
      # We append the tlsCAFile parameter so Mongoose knows where to find the bundle we download in install_dependencies.sh
      - |
        printf "PORT=8001\nNODE_ENV=$NODE_ENV\nMONGODB_URI=${MONGODB_URI}&tlsCAFile=/home/ubuntu/customer/global-bundle.pem\nMSG_QUEUE_URL=$MSG_QUEUE_URL\nEXCHANGE_NAME=$EXCHANGE_NAME\nAPP_SECRET=$APP_SECRET" > .env
  build:
    commands:
      - echo "Build complete for Customer Service"
artifacts:
  base-directory: customer
  files:
    - '**/*'