version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Fixing line endings and permissions..."
      # This fixes the Windows-to-Linux crash issue
      - sed -i 's/\r$//' scripts/*.sh
      - chmod +x scripts/*.sh
artifacts:
  files:
    - '**/*'
  # This is the magic line. It tells CodeBuild: 
  # "Go inside the customer folder and make THAT the root of the zip file"
  base-directory: '.'